//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcc2ModelViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ModelViewerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ModelViewerSettings defaultInstance = ((ModelViewerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ModelViewerSettings())));
        
        public static ModelViewerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAllFunctions {
            get {
                return ((bool)(this["ShowAllFunctions"]));
            }
            set {
                this["ShowAllFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInconsistentStates {
            get {
                return ((bool)(this["ShowInconsistentStates"]));
            }
            set {
                this["ShowInconsistentStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInternalVcc2Variables {
            get {
                return ((bool)(this["ShowInternalVcc2Variables"]));
            }
            set {
                this["ShowInternalVcc2Variables"] = value;
            }
        }
    }
}
