#!/bin/sh

dir=//emicverisoft01/drops/boogie2
src="$dir/$(ls $dir | tail -1)"
echo "Syncing from $src"

rm -rf cache
mkdir cache

all=

for f in * ; do
  all="$all $src/$f"
done
cp -v $all cache || : 

src=cache
for f in * ; do
  test -f $src/$f || continue
  cmp -s $src/$f $f && continue
  # chmod +rwX $f
  echo "SYNC $f"
  cp $src/$f $f
  if [ $f = "z3.exe" ] ; then 
    PATH=$PATH:/cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio\ 9.0/Common7/IDE:/cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio\ 9.0/VC/BIN
    PATH=$PATH:/cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio\ 9.0/Common7/IDE:/cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio\ 9.0/VC/BIN
    editbin.exe /stack:0x8000000 $f /nologo
  fi
done


rm -rf cache
