#!/bin/sh
z3 \
MODEL_PARTIAL=true \
MODEL_VALUE_COMPLETION=false \
MODEL_HIDE_UNUSED_PARTITIONS=false \
MODEL_V1=true \
ASYNC_COMMANDS=false \
PHASE_SELECTION=0 \
RESTART_STRATEGY=0 \
RESTART_FACTOR=1.5 \
NNF_SK_HACK=true \
QI_EAGER_THRESHOLD=100 \
ARITH_RANDOM_INITIAL_VALUE=true \
SORT_AND_OR=false \
CASE_SPLIT=3 \
DELAY_UNITS=true \
DELAY_UNITS_THRESHOLD=16 \
TYPE_CHECK=true \
BV_REFLECT=true \
MODEL=true \
"$@"
